name: Branch Name Pipeline

on:
  push:
    branches:
      - Dev
      - Val
      - Prod

jobs:
  afficher-branche:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher le nom de la branche
        run: 'echo "Branche : ${{ github.ref_name }}"'
