name: Credent pipeline

on: 
  push:
    branches:
      - main

jobs:
  afficher-nom:
    runs-on: ubuntu-latest
    env:
      NOM: ${{ vars.NOM }}

    steps:
      - name: Afficher le nom
        run: 'echo "Nom : $NOM"'

  afficher-prenom:
    runs-on: ubuntu-latest
    env:
      PRENOM: ${{ vars.PRENOM }}

    steps:
      - name: Afficher le prénom
        run: 'echo "Prénom : $PRENOM"'

  afficher-email:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ vars.EMAIL }}

    steps:
      - name: Afficher l'email
        run: 'echo "Email : $EMAIL"'
