name: Hello World Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # <-- C'est cette ligne qui active le déclenchement manuel

jobs:
  say-hello:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Afficher le message
        run: echo "Hello, World!"